# Generated by Django 5.1.2 on 2024-11-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_product_instagram_link_product_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Instagram_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='Instagram_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
